services:
    email-worker:
        container_name: email_worker
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - ./:/app
            - ../../templates:/mnt/templates
