services:
    notification-service-sg:
        container_name: notification-service-sg
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        expose:
            - 8000:8007
        # create bind mount for 2-way sync and watch for development configuration
        volumes:
            - ./src:/app/src
            - ./migrations:/app/migrations:ro # create read-only volume for alembic migrations in development
        develop:
            watch:
                - action: rebuild
                  path: .env

                - action: rebuild
                  path: pyproject.toml

    email-worker:
        container_name: email_worker
        build:
            context: ./workers/email_worker
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - ./workers/email_worker:/app
            - ./templates:/${STORAGE_PATH}/templates

volumes:
    templates:
